baseURL = 'https://til.mariuskimmina.com/'
languageCode = 'en-us'
title = "What I've learned"
theme="archie"
copyright = "© Marius Kimmina"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mariuskimmina"

[[params.social]]
name = "Mastodon"
icon = "mastodon"
url = "https://infosec.exchange/@mariuskimmina"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
